name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  docker-build-push-images-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Private Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_PRIVATE_REGISTRY_NAME }}
          username: ${{ secrets.DOCKER_PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_PRIVATE_REGISTRY_PASSWORD }}

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_PRIVATE_REGISTRY_NAME }}/developer-blog-be-admin:latest

  ec2-pull-stop-remove-run-container-docker:
    needs: ["docker-build-push-images-docker"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: SSH EC2
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_NAME }}@${{ secrets.EC2_HOST_IP_PUBLIC }}

      - name: Login private registry
        run: |
          sudo docker login ${{ secrets.DOCKER_PRIVATE_REGISTRY_NAME }} \
          -u ${{ secrets.DOCKER_PRIVATE_REGISTRY_USERNAME }} \
          -p ${{ secrets.DOCKER_PRIVATE_REGISTRY_PASSWORD }}

      - name: Pull docker image
        run: sudo docker pull ${{ secrets.DOCKER_PRIVATE_REGISTRY_NAME }}/developer-blog-be-admin:latest

      - name: Delete old docker container
        run: sudo docker rm developer-blog-be-admin || true

      - name: Run docker container
        run: |
          sudo docker run \
            -p 1111:1111 \
            -e PORT=1111 \
            -e DB_DIALECT=mysql \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            ${{ secrets.DOCKER_PRIVATE_REGISTRY_NAME }}/developer-blog-be-admin

  