name: CI Pipeline
on:
  push:
    branches: ["main"]
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Private Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_PRIVATE_REGISTRY_NAME }}
        username: ${{ secrets.DOCKER_PRIVATE_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_PRIVATE_REGISTRY_PASSWORD }}

    - name: Build and push images
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_PRIVATE_REGISTRY_NAME }}/developer-blog-be-admin:latest

 